config/routes.rb
Rails.application.routes.draw do
  resources :fuel_options

  resources :fuel_calculators
  
  devise_for :users

  unauthenticated do
    root to: "main#index", as: :unauthenticated_root
  end

  authenticated do
    root to: "main#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/fuel_calculator.rb
class FuelCalculator < ApplicationRecord
  include ClassyEnum::ActiveRecord

  has_one :user

  classy_enum_attr :temperature, class_name: 'TemperatureRange'
  classy_enum_attr :estimate_start, class_name: 'TimeBeforeRunning'

  def convert_lb_to_kg
    kg = 2.2046
    (weight.to_f / kg).round(2)
  end

  def convert_miles_km
    (distance.to_f * 1.609344).round(2)
  end

  def elevation_gain_km
    (elevation.to_f / 3280.84).round(2)
  end

  def average_pace_mile
    (estimate_time.to_f / distance.to_f).round(2)
  end

  def carbohydrates
    (estimate_start.time_before_running_multiplier * convert_lb_to_kg).round(2)
  end

  def caloric_burn_rate
    (((elevation_gain_km * average_pace_mile) + convert_miles_km) * convert_lb_to_kg).round(2)
  end

  def formula_reference
    estimate_time.to_f / 60
  end

  def running_power
    ((((elevation_gain_km * 10 ) + convert_miles_km) * 1000) / (formula_reference * 3600) * 1.04 * convert_lb_to_kg).round(2)
  end

  def while_running_carbohydrates
    ((((((elevation_gain_km * 10) + convert_miles_km) * convert_lb_to_kg) / formula_reference) / 4) * 0.32).round(2)
  end

  def while_running_sodium
    ((temperature.fluid / 33.814) * 700).round(2)
  end
end

app/models/fuel_option.rb
class FuelOption < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fuel_calculators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :bio, :first_name, :last_name, :username])
  end

  private

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/fuel_calculators_controller.rb
class FuelCalculatorsController < ApplicationController
  before_action :set_fuel_calculator, only: %i[ show edit update destroy ]

  def index
    @fuel_calculators = FuelCalculator.all
  end

  def show
  end

  def new
    @fuel_calculator = FuelCalculator.new
  end

  def edit
  end

  def create
    @fuel_calculator = FuelCalculator.new(fuel_calculator_params)

    respond_to do |format|
      if @fuel_calculator.save
        format.html { redirect_to fuel_calculator_url(@fuel_calculator), notice: "Fuel calculator was successfully created." }
        format.json { render :show, status: :created, location: @fuel_calculator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fuel_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fuel_calculator.update(fuel_calculator_params)
        format.html { redirect_to fuel_calculator_url(@fuel_calculator), notice: "Fuel calculator was successfully updated." }
        format.json { render :show, status: :ok, location: @fuel_calculator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fuel_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fuel_calculator.destroy

    respond_to do |format|
      format.html { redirect_to fuel_calculators_url, notice: "Fuel calculator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_fuel_calculator
      @fuel_calculator = FuelCalculator.find(params[:id])
    end

    def fuel_calculator_params
      params.require(:fuel_calculator).permit(:weight, :distance, :elevation, :estimate_time, :temperature, :estimate_start)
    end
end

app/controllers/fuel_options_controller.rb
class FuelOptionsController < ApplicationController
  before_action :set_fuel_option, only: %i[ show edit update destroy ]

  def index
    @fuel_options = FuelOption.all
  end

  def show
  end

  def new
    @fuel_option = FuelOption.new
  end

  def edit
  end

  def create
    @fuel_option = FuelOption.new(fuel_option_params)

    respond_to do |format|
      if @fuel_option.save
        format.html { redirect_to fuel_option_url(@fuel_option), notice: "Fuel option was successfully created." }
        format.json { render :show, status: :created, location: @fuel_option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fuel_option.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fuel_option.update(fuel_option_params)
        format.html { redirect_to fuel_option_url(@fuel_option), notice: "Fuel option was successfully updated." }
        format.json { render :show, status: :ok, location: @fuel_option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fuel_option.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fuel_option.destroy

    respond_to do |format|
      format.html { redirect_to fuel_options_url, notice: "Fuel option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_fuel_option
      @fuel_option = FuelOption.find(params[:id])
    end

    def fuel_option_params
      params.fetch(:fuel_option, {})
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @users = User.all.order(created_at: :desc)
  end

  def edit
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:avatar, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fuel_calculators_helper.rb
module FuelCalculatorsHelper
end

app/helpers/fuel_options_helper.rb
module FuelOptionsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/fuel_calculators/_form.html.haml
= form_for @fuel_calculator do |f|
  = render "shared/error_messages", object: f.object

  .form-outline.mb-4
    = f.label :weight
    = f.text_field :weight, class: "form-control", autofocus: true
  .form-outline.mb-4
    = f.label :distance
    = f.text_field :distance, class: "form-control", autofocus: true
  .form-outline.mb-4
    = f.label :elevation
    = f.text_field :elevation, class: "form-control", autofocus: true
  .form-outline.mb-4
    = f.label :estimate_time
    = f.text_field :estimate_time, class: "form-control", autofocus: true
  .form-outline.mb-4
    = f.label :temperature
    = f.select :temperature, TemperatureRange.map{ |p| [p.text, p] }, {}, {class: "form-control"}

  .form-outline.mb-4
    = f.label :estimate_start
    = f.select :estimate_start, TimeBeforeRunning.map{ |p| [p.text, p] }, {}, {class: "form-control"}

  = f.submit 'Save', class: "btn btn-lg w-100 btn-primary mb-3"

app/views/fuel_calculators/edit.html.haml
.container.mt-5
  .row.d-flex.justify-content-center.align-items-center.h-100
    .col-12.col-md-8.col-lg-6.col-xl-5
      .card.shadow-2-strong{style: "border-radius: 1rem;"}
        .card-body.p-5
          %h2.text-center.mb-3
            Edit Fuel Calculator
          %p.text-muted.text-center.mb-4
            Add numbers here.

          = render 'form'
          = link_to 'Show', @fuel_calculator
          \|
          = link_to 'Back', fuel_calculators_path

app/views/fuel_calculators/index.html.haml
%h2 Fuel Calculator

%table
  %thead
    %tr
      %th Weight
      %th Distance
      %th Elevation
      %th Estimate time
      %th Temperature
      %th Estimate start
      %th
      %th
      %th

  %tbody
    - @fuel_calculators.each do |fuel_calculator|
      %tr
        %td= fuel_calculator.weight
        %td= fuel_calculator.distance
        %td= fuel_calculator.elevation
        %td= fuel_calculator.estimate_time
        %td= fuel_calculator.temperature
        %td= fuel_calculator.estimate_start
        %td= link_to 'Show', fuel_calculator
        %td= link_to 'Edit', edit_fuel_calculator_path(fuel_calculator)
        %td= link_to 'Destroy', fuel_calculator, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Fuel calculator', new_fuel_calculator_path

app/views/fuel_calculators/new.html.haml
.container.mt-5
  .row.d-flex.justify-content-center.align-items-center.h-100
    .col-12.col-md-8.col-lg-6.col-xl-5
      .card.shadow-2-strong{style: "border-radius: 1rem;"}
        .card-body.p-5
          %h2.text-center.mb-3
            Fuel Calculator
          %p.text-muted.text-center.mb-4
            Add numbers here.

          = render "form"
          = link_to "Back", fuel_calculators_path

app/views/fuel_calculators/show.html.haml
%p
  %b Weight:
  = @fuel_calculator.weight
  %b Body Weight in Kilograms
  = @fuel_calculator.convert_lb_to_kg
%p
  %b Distance:
  = @fuel_calculator.distance
  %b Distance in Kilometers:
  = @fuel_calculator.convert_miles_km
%p
  %b Elevation:
  = @fuel_calculator.elevation
  %b Elevation Gain in Kilometers
  = @fuel_calculator.elevation_gain_km
%p
  %b Estimate time:
  = @fuel_calculator.estimate_time
  %b Average Pace/Mile:
  = @fuel_calculator.average_pace_mile
%p
  %b Temperature:
  = @fuel_calculator.temperature.text
%p
  %b Estimate start:
  = @fuel_calculator.estimate_start.text
  %hr

%p
  %h4 Pre-run Fuel Target
  %b Carbohydrates:
  = @fuel_calculator.carbohydrates
  %hr

%p
  %h4 Expected Workout Totals
  %b Caloric Burn Rate
  = @fuel_calculator.caloric_burn_rate
  %br
  %b Running Power
  = @fuel_calculator.running_power
  %hr

%p
  %h4 Long run/race fueling target
  %b These amounts should be consumed hourly while running
  %p
  %b Carbohydrates:
  = @fuel_calculator.while_running_carbohydrates
  %br
  %b Sodium:
  = @fuel_calculator.while_running_sodium
  %br
  %b Water:
  = @fuel_calculator.temperature.fluid

= link_to 'Edit', edit_fuel_calculator_path(@fuel_calculator)
\|
= link_to 'Back', fuel_calculators_path

app/views/fuel_options/_form.html.haml
= form_for @fuel_option do |f|
  = render "shared/error_messages", object: f.object

  -# .form-outline.mb-4
  -#   = f.label :weight
  -#   = f.text_field :weight, class: "form-control", autofocus: true
  -# .form-outline.mb-4
  -#   = f.label :distance
  -#   = f.text_field :distance, class: "form-control", autofocus: true
  -# .form-outline.mb-4
  -#   = f.label :elevation
  -#   = f.text_field :elevation, class: "form-control", autofocus: true
  -# .form-outline.mb-4
  -#   = f.label :estimate_time
  -#   = f.text_field :estimate_time, class: "form-control", autofocus: true
  -# .form-outline.mb-4
  -#   = f.label :temperature
  -#   = f.select :temperature, TemperatureRange.map{ |p| [p.text, p] }, {}, {class: "form-control"}
  -#
  -# .form-outline.mb-4
  -#   = f.label :estimate_start
  -#   = f.select :estimate_start, TimeBeforeRunning.map{ |p| [p.text, p] }, {}, {class: "form-control"}

  = f.submit 'Save', class: "btn btn-lg w-100 btn-primary mb-3"

app/views/fuel_options/edit.html.haml
.container.mt-5
  .row.d-flex.justify-content-center.align-items-center.h-100
    .col-12.col-md-8.col-lg-6.col-xl-5
      .card.shadow-2-strong{style: "border-radius: 1rem;"}
        .card-body.p-5
          %h2.text-center.mb-3
            Edit Fuel Option
          %p.text-muted.text-center.mb-4
            Add numbers here.

          = render 'form'
          = link_to 'Show', @fuel_calculator
          \|
          = link_to 'Back', fuel_options_path

app/views/fuel_options/index.html.haml
%h2 Fuel Option


%br
%table.table.caption-top
  %caption
    Fueling Targets - Calculated from the data you entered in the Fuel Calculator
  %thead
    %tr
      %th{:scope => "col"}
        \#
      %th{:scope => "col"}
        Pre-run fuel target
      %th{:scope => "col"}
        Long run/race fueling target
        %br
        (needed each hour)
      %th{:scope => "col"}
        Long run/race fueling target
        %br
        (needed each hour)
    %tr
      %th{:scope => "col"}

      %th{:scope => "col"}
        Carbohydrates
      %th{:scope => "col"}
        Carbohydrates
      %th{:scope => "col"}
        Sodium
  %tbody
    %tr
      %th{:scope => "row"} 1
      %td= @fuel_calculator.caloric_burn_rate
      %td= @fuel_calculator.while_running_carbohydrates
      %td= @fuel_calculator.while_running_sodium



  %tbody
    - @fuel_options.each do |fuel_option|
      %tr
        %td= link_to 'Show', fuel_option
        %td= link_to 'Edit', edit_fuel_option_path(fuel_option)
        %td= link_to 'Destroy', fuel_option, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Fuel option', new_fuel_option_path

app/views/fuel_options/new.html.haml
.container.mt-5
  .row.d-flex.justify-content-center.align-items-center.h-100
    .col-12.col-md-8.col-lg-6.col-xl-5
      .card.shadow-2-strong{style: "border-radius: 1rem;"}
        .card-body.p-5
          %h2.text-center.mb-3
            Fuel Option
          %p.text-muted.text-center.mb-4
            Add numbers here.

          = render "form"
          = link_to "Back", fuel_options_path

app/views/fuel_options/show.html.haml
= link_to 'Edit', edit_fuel_option_path(@fuel_option)
\|
= link_to 'Back', fuel_options_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Marathon
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  %body
    = render "shared/navigation"
    .container.mt-4
      = render "shared/flash"
      = yield

app/views/main/index.html.haml
- if user_signed_in?
  .p-4.shadow-4.rounded-3.text-center{style: "background-color: hsl(0, 0%, 94%);"}
    %h2 Let's Calculate!
    %p
      This is a simple hero unit, a simple jumbotron-style component for calling extra
      attention to featured content or information.
    %hr.my-4/
    %p
      It uses utility classes for typography and spacing to space content out within the
      larger container.

- else
  .p-4.shadow-4.rounded-3.text-center{style: "background-color: hsl(0, 0%, 94%);"}
    %h2 Welcome to Marathon!
    %p
      This is a simple hero unit, a simple jumbotron-style component for calling extra
      attention to featured content or information.
    %hr.my-4/
    %p
      It uses utility classes for typography and spacing to space content out within the
      larger container.

    = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary mr-3'
    = link_to 'Login', new_user_session_path, class: 'btn btn-outline-secondary'

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger.mt-2
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash.html.haml
- if notice
  .alert.alert-info.my-3{:role => "alert"}
    = notice
- if alert
  .alert.alert-warning.my-3{:role => "alert"}
    = alert

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.bg-gradient
  .container
    = link_to "Marathon", root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarText", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarText.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        -# = link_to "Users", users_path, class: "nav-item nav-link"
      %ul.navbar-nav.mb-2.mb-lg-0
        - if user_signed_in?
          -# = image_tag avatar_url_for(current_user, size: 24), class: "rounded-circle mr-1 nav-item nav-link"
          -# = link_to Current.user.username, user_path(current_user.id), class: "nav-item nav-link"
          = link_to "Fuel Calculator", fuel_calculators_path, class: "nav-item nav-link me-2"
          = link_to "Fuel Options", fuel_options_path, class: "nav-item nav-link me-2"
          = link_to "Settings", edit_user_registration_path, class: "nav-item nav-link me-2"
          = link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-item nav-link"

        - else
          = link_to "Sign up", new_user_registration_path, class: "nav-item nav-link"
          = link_to "Login", new_user_session_path, class: " nav-item nav-link"

app/views/shared/_stats.html.haml
- @user ||= current_user
.d-flex.justify-content-start.rounded-3.p-2.mb-2
  %div
    %p.small.text-muted.mb-1
      Posts
    %p.mb-0 41

  .px-3
    %p.small.text-muted.mb-1
      Followers
    %p.mb-0
      %a{href: "#{followers_user_path(@user)}"}
        = @user.followers.count

  %div
    %p.small.text-muted.mb-1
      Following
    %p.mb-0
      %a{href: "#{following_user_path(@user)}"}
        = @user.following.count